name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm rebuild

      # Start your application in the background
    - run: npm start &

      # Wait for your application to be ready (e.g., localhost:3000)
    - name: Wait for app to start
      run: npx wait-on http://localhost:3000

      # Add more steps as needed (e.g., deploy, publish, etc.)
